defaults:
  - dataset: pssdp_mac

dataset:
 name: ???
 path: ???
 training_data: ${dataset.path}/train.csv.gz
 testing_data: ${dataset.path}/test.csv.gz
 prediction_data: ${dataset.path}predictions/pssdp_predictions.csv
 model_data: ${dataset.path}models/
 best_model: ${model_data}models/best_model.pth

