context = r"""Lionel Colin Matthews, GC, MC (15 August 1912 – 2 March 1944) was an Australian Army officer in World War II. He was posthumously awarded the George Cross, the highest award for heroism or courage not in the face of the enemy, that could be awarded to a member of the Australian armed forces at the time. Matthews was born in Adelaide, South Australia, and was schooled there before moving to Victoria. He trained as a signalman in the Royal Australian Naval Reserve before joining the Militia in April 1939. Commissioned as an officer in the Australian Corps of Signals, Matthews transferred to the 8th Division of the Second Australian Imperial Force after the outbreak of World War II.

Sent to Singapore with the rest of the 8th Division, Matthews served as the brigade signals officer of the 27th Brigade during the Malayan campaign and the Battle of Singapore, and at the surrender of Singapore he became a prisoner of war (POW). While in captivity he was awarded the Military Cross for displaying a high standard of courage, energy and ability while maintaining communications under fire in the earlier fighting. In July 1942, he was a member of a group of POWs sent to the Sandakan POW camp in British North Borneo. There, Matthews established an intelligence network, collecting information, weapons, medical supplies and radio parts, and made contact with organizations outside the camp, including Filipino guerrillas who assisted POWs to escape.

In July 1943, members of his organisation were betrayed, and Matthews and others were arrested, beaten, tortured and starved by their Japanese captors. Matthews refused to provide any information on his organization or its members to the Kenpeitai, and was executed by firing squad at Kuching, Sarawak, in March 1944. After the war, he was posthumously awarded the George Cross in recognition of his gallant and distinguished services while a POW in Japanese hands.

Early life and career
Lionel Colin Matthews was born in the Adelaide inner north-eastern suburb of Stepney on 15 August 1912, the third child of Edgar Roy Matthews, a plumber, and his wife Ann Elizabeth née Jeffery. He attended East Adelaide Public School and Norwood High School. After graduation, he started work as a salesman in a department store. In his spare time he was an assistant scoutmaster at 1st Kensington Sea Scouts from 1931, and excelled at swimming and was a handy amateur boxer. In 1930 he enlisted in the part-time Militia and served with the 10th Battalion; then transferred to the Royal Australian Naval Reserve and trained as a signalman. On 26 December 1935 he married (Lorna) Myrtle Lane at St Matthew's Church, Kensington. Lorna was 21 at the time, and working as a packer. In 1937–1938, Lionel was engaged in social work at Pentridge Prison in Melbourne, a role sponsored by the Boy Scout's Association.[1][2] After they moved to Melbourne, Matthews transferred back to the Militia and was posted to the 3rd Division Signals in April 1939.[1][2] Lionel and Lorna had one child, Lionel David (known as David).[3]

After the outbreak of World War II, Matthews was promoted to lieutenant on 18 January 1940.[2] He transferred from the Militia to the all-volunteer Second Australian Imperial Force (Second AIF) at Caulfield, Victoria, on 10 June and was allocated to the 8th Division Signals.[4] He was formally appointed as a lieutenant in the Second AIF on 1 July.[5] Matthews underwent training in Victoria and later in New South Wales, including a course at the Army School of Signals. The 8th Division Signals embarked aboard the converted ocean liner RMS Queen Mary for Singapore on 3 February 1941, arriving on 18 February.[6]

Malayan campaign
Matthews wore a clipped moustache, and was nicknamed "The Duke" because of his physical resemblance to Prince Henry, Duke of Gloucester. He was posted as the signals officer for the 27th Brigade, which arrived in Malaya in August.[1] The Australians formed part of a defensive garrison that had been established due to growing concerns about a possible war with Japan. Under the command of Brigadier Duncan Maxwell, the brigade moved to Jemaluang,[7] as part of the 8th Division under Major General Gordon Bennett. Consisting of only two brigades, the division was tasked with securing the eastern part of Johore. Bennett pushed the 22nd Brigade forward around Mersing and held the 27th Brigade back as his reserve. In December 1941 the Japanese invaded Malaya, and the 27th Brigade was committed to the Allied resistance in the Malayan campaign, although the initial stages of the fighting were in the north, away from the Australians' area of responsibility.[8]

As the Japanese quickly advanced down the Malay Peninsula, the Australian force was reorganised. While the 22nd Brigade assumed control of eastern Johore, the 27th moved to the west where it was joined by several British and Indian units to create an ad hoc formation called "Westforce" under Bennett's command. Throughout January 1942, the brigade fought delaying actions around the west coast of the Malay Peninsula, including the Battle of Gemas and the wider Battle of Muar, as the Allies were pushed back towards Singapore.[8] The Japanese advance continued, and eventually the 27th Brigade withdrew to Simpang Renggam through Yong Peng and Ayer Hitam. As efforts were made to delay the Japanese, the brigade headquarters temporarily took several British units under its command. The brigade carried out delaying actions before withdrawing to Yong Peng, and then fought to maintain control of the crossroad around Ayer Hitam.[9] Matthews was promoted to captain on 21 January.[5] On 28 January, further fighting occurred around the Namazie rubber plantation, where a strong Japanese attack was repelled, forcing the Japanese to carry out a flanking action that exploited a gap in the line to the west. This nearly rolled through the 27th Brigade, forcing it to withdraw.[9] By the end of January the Allied forces were withdrawn to Singapore, and defensive preparations began to repel a Japanese assault across the Johore Strait.[8]

Battle of Singapore
After the Malayan campaign, the 27th Brigade initially took part in the defence of Singapore by defending the Causeway area. The Japanese assault began on the night of 8/9 February, and fell largely on the 22nd Brigade's sector, where two Japanese divisions landed during the Battle of Sarimbun Beach. The brigade's troops managed to hold their area, fending off some flanking efforts by the Japanese along the Kranji River,[10] and the 2/29th Battalion was sent south to help bolster the 22nd Brigade.[8] The following night, another Japanese landing fell in the 27th Brigade's area,[10] and heavy fighting took place during the Battle of Kranji. The Japanese suffered heavy casualties from the defenders' machine guns and mortars, as well as burning oil that had been sluiced across the water.[11] The attacking troops managed to establish a beachhead and the 27th Brigade's headquarters was subsequently cut off from its battalions, as the Allies were pushed back towards the centre of the island. As the Allied perimeter continued to shrink around the town, the 8th Division units were brought together around Tanglin Barracks, where they remained until the garrison surrendered on 15 February.[10]

Prisoner of war
Matthews was initially interned in the Changi prisoner-of-war camp on Singapore.[1] In May, captured elements of Malaya Command authorised the award of the Military Cross to Matthews for his actions at Gemas and on Singapore. The citation, which was not officially gazetted until 8 January 1946, read:[12][13]

During operations at Gemas this officer succeeded in maintaining cable communications between his Brigade HQ and units under heavy artillery and mortar fire and aerial bombardment, displaying a high standard of courage, energy and ability in doing so. Later during the operation on Singapore Island Capt Matthews succeeded in laying a cable over ground strongly patrolled by the enemy and thus restoring communication between his Divisional HQ and the HQ of a Brigade at a critical period.

In July, "B" Force, consisting of nearly 1,500 Australian prisoners-of-war (POWs), including Matthews, was sent to the Sandakan POW camp in occupied British North Borneo. Once they arrived, Matthews set up a complex intelligence-gathering network that was linked to several key figures; including J. P. Taylor, an Australian doctor in charge of the local hospital, as well as Europeans interned on nearby Berhala Island. Matthews and his second-in-command, Lieutenant R. G. Wells, also established links with Asians, some of whom were Chinese, along with members of the British North Borneo Constabulary, which was operating under Japanese supervision. The police passed them information, maps, a revolver, radio parts and medical supplies.[1][2] Their smuggling of medical supplies saved dozens of lives.[14]

By September 1942, Matthews and Wells had consolidated and expanded their organisation. All intelligence gathered was passed to Matthews and collated. He managed to make contact with Filipino resistance fighters operating on the Sulu Archipelago in the south-west Philippines, who assisted Australian POWs to escape. The Japanese transferred the civilian internees from Berhala Island to the Batu Lintang camp near Kuching in Sarawak in January 1943.[1][2] Matthews had gained the trust of the Governor of North Borneo, Robert Smith, who had been interned nearby and, when the civilian internees departed he was placed in effective command of the British North Borneo Constabulary despite being a POW. While he had several opportunities to escape, Matthews decided to remain with his fellow POWs and continue running his covert organisation at great risk to himself.[15] He made plans to rise up against the Japanese if the Allies landed in Borneo, and initiated the building of a radio transmitter.[1][2]

In July 1943, four Chinese members of Matthews' intelligence network were betrayed to the Japanese. Tortured, they confessed to providing radio parts. The Japanese then arrested Matthews, Wells, Taylor and other members of the organisation. They were beaten, tortured and starved as part of their interrogation, then transported to Kuching. Matthews was sentenced to death, along with two members of the British North Borneo Constabulary and six other Asians. Throughout their confinement, Matthews had encouraged the other suspects, and had refused to divulge any information about their activities. Matthews was executed by a firing squad on 2 March 1944, refusing the offer of a blindfold.[1][2]

As well as the Military Cross, he was entitled to the 1939–1945 Star, the Pacific Star, the Defence Medal, the War Medal 1939–1945, and the Australia Service Medal 1939–1945.[16] Matthews' body was later exhumed and reinterred in the Labuan War Cemetery.[17] Matthews' older brother Geoffrey commanded the 9th Battalion in the latter stages of World War II, and was awarded the Distinguished Service Order.[1][18]

"""

from transformers import pipeline

nlp = pipeline("question-answering")

result = nlp(question="What war did Lionel Colin Matthews fight in?", context=context)
print(f"Answer: '{result['answer']}', score: {round(result['score'], 4)}, start: {result['start']}, end: {result['end']}")

result = nlp(question="What medals did he win?", context=context)
print(f"Answer: '{result['answer']}', score: {round(result['score'], 4)}, start: {result['start']}, end: {result['end']}")